### ISSUE TITLE
Visual Error uploading Logo

### ISSUE THREAD

**Issue by joecharman** [kodersha/humhub-theme-flathub#10]
When uploading a logo in admin I get this issue (image attached).

Whatever size the image is it still doesn't show correctly, instead it is hidden from view (up).
![logo-error](https://cloud.githubusercontent.com/assets/11601684/14831641/8d667f96-0bee-11e6-8cff-4642a6224a35.png)

**Comment by kodersha** [comment]
Hi! Please, redownload this files from github:
../css/theme.css
../views/widgets/logo.php
