### ISSUE TITLE
Error on login screen

### ISSUE THREAD

**Issue by Shashwatsh** [kodersha/humhub-theme-flathub#14]
PHP Notice – yii\base\ErrorException

Undefined variable: registerModel
on localhost
when test it on the server it says

PHP Fatal Error – yii\base\ErrorException

Call to a member function getAttributeLabel() on null

in /home/softwar1/public_html/codeduck.net/themes/flathub/views/user/auth/login.php

**Comment by Lokyaziis** [comment]
still no solution ??!!

**Comment by WebCrew** [comment]
issue got fixed by latest pull request

**Comment by Felli** [comment]
These two pulls should fix the issue #15 & #17 I'd use the newer one to be safe. :smile:

**Comment by WebCrew** [comment]
@Felli yes I just checked it yesterday after I asked you :) 

Sometimes my rotten old brain needs a bit longer to understand hahahahahahah

The errorException is fixed now ;)
