### ISSUE TITLE
[Fixed]Error when I try to Logout. and then it doesn't work. 

### ISSUE THREAD

**Issue by mansi-manhas** [kodersha/humhub-theme-flathub#20]
Error:
PHP Notice – yii\base\ErrorException

Undefined variable: registerModel

Screenshot :
![image](https://cloud.githubusercontent.com/assets/18692751/23364420/02a11d7a-fd25-11e6-8e2d-7d6211bb03b9.png)

**Comment by WebCrew** [comment]
Check it out please: https://github.com/sasha-travkina/humhub-themes-flathub/pull/15

**Comment by mansi-manhas** [comment]
Thank you. 👍
