### ISSUE TITLE
Code Duplication

### ISSUE THREAD

**Issue by Felli** [kodersha/humhub-theme-flathub#4]
Via Scrutinizer
views/layouts/main.php

```
120     
    <?php if (isset($this->context->subLayout) && $this->context->subLayout != "") : ?>
121     
        <?php echo $this->render($this->context->subLayout, array('content' => $content)); ?>
122     
    <?php else: ?>
123     
        <?php echo $content; ?>
124     
    <?php endif; ?>
```

views/user/layouts/main.php

```
82      
        <?php if (isset($this->subLayout) && $this->subLayout != "") : ?>
83      
            <?php echo $this->renderPartial($this->subLayout, array('content' => $content)); ?>
84      
        <?php else: ?>
85      
            <?php echo $content; ?>
86      
        <?php endif; ?>
```

views/user/layouts/main_auth.php

```
68      
        <?php if (isset($this->subLayout) && $this->subLayout != "") : ?>
69      
            <?php echo $this->renderPartial($this->subLayout, array('content' => $content)); ?>
70      
        <?php else: ?>
71      
            <?php echo $content; ?>
72      
        <?php endif; ?>
```

**Comment by WebCrew** [comment]
For my opinion in that situation Scrutinizer is false cause it does not respect how Yii2 is doing things. Within pure php and Yii2 things be done differently and both syntrax does have other ways to get things done. So for my opinion this is not a issue and all is done corectly. Cause if thats realy a error / issue of dublicated code then the whole HumHub system has that problem and I dont think the HH devs have not thought about such things. I just wanted to mention this, but I`m not a php or Yii2 professional and I can be wrong.

**Update:**
I just checked out Scrutinizer and as I thought it has no Yii support right now only for basic PHP, so one could not use the tool to debug a Yii based application with it.

**Comment by Felli** [comment]
Code duplication can cause load time issues if not put in check, this is what Scrutinizer is saying, it's not necessarily an issue for the most part, just an issue nonetheless. :wink:

**Comment by WebCrew** [comment]
Yes You are right code dublication is always not good :+1: but sadly thats how HumHub is doing it in some of its templates. I dont know if with HumHub thats a must have to generate some codes double or if it is a bug, but so or so You are right, its not good to use code parts dublicated. But cause of the GitHub issue here I think nothing must be changed.
