### ISSUE TITLE
Minor/Informational Code Issues

### ISSUE THREAD

**Issue by Felli** [kodersha/humhub-theme-flathub#5]
Via Scrutinizer
views/users/layouts/main.php

```
1       
<?php
91      
            $('body').find(':checkbox, :radio').flatelements();
92      
        </script>
93      
94      
        <?php //echo HSetting::GetText('trackingHtmlCode'); ?>
```

> 67% of this comment could be valid code. Did you maybe forget this after debugging?

views/users/widgets/ProfileMenu.php

```
1       
<?php
40      
            'isActive' => (Yii::$app->controller->id == "profile" && Yii::$app->controller->action->id == "index"),
41      
        ));
42      
43      
        //if (Yii::$app->getController()->getUser()->profile->about != "") {
```

Quoted from Scrutinizer

> 62% of this comment could be valid code. Did you maybe forget this after debugging?

```
44      
        $this->addItem(array(
45      
            'label' => Yii::t('UserModule.widgets_ProfileMenuWidget', 'About'),
46      
            'group' => 'profile',
64      
65      
}
66      
67      
?>
```

Also quoted from Scrutinizer

> It is not recommended to use PHP's closing tag ?> in files other than templates.

**Comment by WebCrew** [comment]
Does Scrutinizer support Yii2? Cause if it has no Yii2 syntrax support the issues dont have to be a error or bug within the files. In Yii2 some things be done differently to pure php, thats why I`m asking.

**Comment by Felli** [comment]
If I remember right, it supports all known frameworks, Yii included. :+1:

**Comment by WebCrew** [comment]
I just checked out Scrutinizer and as I thought it has no Yii support right now only for basic PHP, so one could not use the tool to debug a Yii based application with it, but Your idea was cool and its always good if more peoples get their eyes on things so I find it good that You check things :+1: 

Look Sarah: https://scrutinizer-ci.com/docs/build/environment

**Comment by Felli** [comment]
Might wanna look a little closer into Scrutinizer. :wink:
https://scrutinizer-ci.com/docs/reviews/configure_automated_checks

**Comment by Felli** [comment]
Also the devs themselves use Scrutinizer for the HumHub project itself. :+1:

**Comment by WebCrew** [comment]
If the HumHub devs also use it I wonder why they dont eliminate the code dublications cause they are in more HumHub parts as the ones here at the FlatHub theme. But as I told thats only my opinion and I`m not a PHP nor a Yii professional, thats only my opinion and it can be wrong.

If HumHub devs using it then they have setup other software to use with that tool like mentioned here:
https://scrutinizer-ci.com/docs/guides/install_custom_software

But by default Scrutinizer has no Yii support ( I`m NOT save about it but I cant read about Yii within Scrutinizer) and for my opinion the debuging cant be used by default, have You setup a Yii developer environment into Scrutinizer to debug HumHub?

**Comment by Felli** [comment]
Might have something to do with limited time and the small team of developers they have on staff, this and Yii2 could still have some leftover bugs within it's design that could in fact be causing this. I'll do more research on this when I'm able to, for now I'm looking over a few modules as well as a project that I'm starting up for Yii1/Yii2 developers called @GreenVolume I'm hoping this could help the development of more themes & modules, even possibly extensions for yii1! :+1:

**Comment by WebCrew** [comment]
Thats realy cool from You, I love to see more peoples like You which offer a bit of their sparetime to check other repositories out and to help a bit :+1:

**Comment by Felli** [comment]
@WebCrew thanks! :smiley:

**Comment by WebCrew** [comment]
You`re welcome @Felli keep up rocking and rolling :)
