### ISSUE TITLE
Feature Request: Color Grid

### ISSUE THREAD

**Issue by Felli** [kodersha/humhub-theme-flathub#7]
Would it be possible to replace the Night/Day with a color grid, I'm sure this would open up the theme for better possibilities. :smile:

**Comment by kodersha** [comment]
Hi. You propose add more colors?

**Comment by Felli** [comment]
Not exactly, more of opening the theme up for design for the users, meaning allowing users to choose what colors they want to use. I hope that is a better description of what I'm asking about. :smiley:

**Comment by kodersha** [comment]
Well... I'll think about it. Thanks you for idea.
